version: '3.9'

services:
  web:
    build: .
    command: gunicorn sugangAssitant.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/vol/web/static
    expose:
      - "8000"
    environment:
      - DEBUG=0
      - DB_HOST=db
      - DB_NAME=django
      - DB_USER=django
      - DB_PASS=django
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/vol/web/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
